teleport:
  # teleport is a subsection configuring teleport integration with gravity
  data_dir: /var/lib/gravity/site/teleport
  ciphers:
    - aes128-gcm@openssh.com
    - aes128-ctr
    - aes192-ctr
    - aes256-ctr
  kex_algos:
    - curve25519-sha256@libssh.org
    - ecdh-sha2-nistp256
    - ecdh-sha2-nistp384
    - ecdh-sha2-nistp521
  mac_algos:
    - hmac-sha2-256-etm@openssh.com
    - hmac-sha2-256

auth_servers:
  - 127.0.0.1:3025
auth_service:
  # auth is authentication and authorization server for users and hosts
  # it acts like SSH user CA authority and host CA authority
  enabled: true
  cluster_name: apiserver
proxy_service:
  # proxy starts web and ssh proxy that allow inbound connections from remote nodes
  enabled: true
