apiVersion: v1
kind: Pod
metadata:
  name: debug
  labels:
    app: debug
spec:
  containers:
  - name: debug
    image: leader.telekube.local:5000/gravitational/debian-tall:buster
    command: ['/bin/sh', '-c', 'sleep 3600']
    volumeMounts:
    - mountPath: /rootfs
      name: rootfs
    securityContext:
      runAsUser: 0
  volumes:
  - name: rootfs
    hostPath:
      path: /
